// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateButton('save_button', { onclick: 'sync', rightImageWidth: 3, leftImageWidth: 3, text: 'sync' });
    CreateText('status_text', { text: 'Please Wait...' });
    CreateShape('topRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateText('api_input_label', { text: 'Enter your API Key here:' });
    CreateButton('stikkit_button', { rightImageWidth: 16, leftImageWidth: 5, text: 'Stikkits', onclick: 'showStikkitList' });
    CreateButton('delete_button', { onclick: 'deleteOrCancelStikkit', rightImageWidth: 3, leftImageWidth: 3, text: 'delete' });
    CreateText('email_and_url', { text: 'queries' });
    CreateText('credits', { text: 'James Adam' });
    CreateText('version_label', { text: 'v0.8' });
}
window.addEventListener('load', setupParts, false);
